"""Push the model cards in hub_cards/ to their Hub repos as README.md.

Cards are generated by `scripts/build_model_cards.py` from the committed result
JSON. This script refuses to push stale cards, so the Hub can never disagree
with the repository's own numbers.

Usage:
    HF_TOKEN=hf_... python scripts/push_model_cards.py            # push all
    HF_TOKEN=hf_... python scripts/push_model_cards.py --dry-run  # validate only
    HF_TOKEN=hf_... python scripts/push_model_cards.py --only connections-rl-grpo-7b
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CARDS_DIR = ROOT / "hub_cards"

# repo-name suffixes under the authenticated user's namespace
REPOS = [
    "connections-rl-sft",
    "connections-rl-grpo",
    "connections-rl-sft-7b",
    "connections-rl-grpo-7b",
    "connections-rl-grpo-7b-seed1",
    "connections-rl-grpo-7b-seed2",
    "connections-rl-grpo-1.5b-seed1",
    "connections-rl-grpo-1.5b-seed2",
]

# Dataset repos: {card filename stem: repo name}. These need repo_type="dataset";
# uploading them as models silently targets a different (usually nonexistent) repo.
DATASET_CARDS = {"dataset-connections-rl-results": "connections-rl-results"}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="validate without uploading")
    ap.add_argument("--only", action="append", default=None, help="push a single repo (repeatable)")
    ap.add_argument(
        "--skip-staleness-check",
        action="store_true",
        help="push even if cards differ from what build_model_cards.py would emit",
    )
    args = ap.parse_args(argv)

    # 1. cards must be regenerable from the committed results
    if not args.skip_staleness_check:
        sys.path.insert(0, str(ROOT / "scripts"))
        from build_model_cards import main as build_main

        if build_main(["--check"]) != 0:
            print("Refusing to push stale cards. Run: python scripts/build_model_cards.py")
            return 1

    # (card stem, repo name, repo_type)
    all_targets = [(r, r, "model") for r in REPOS]
    all_targets += [(stem, repo, "dataset") for stem, repo in DATASET_CARDS.items()]
    if args.only:
        all_targets = [t for t in all_targets if t[1] in args.only or t[0] in args.only]
        if not all_targets:
            print(f"No card matches --only {args.only}", file=sys.stderr)
            return 1

    missing = [s for s, _, _ in all_targets if not (CARDS_DIR / f"{s}.md").exists()]
    if missing:
        print(f"Missing cards: {', '.join(missing)}", file=sys.stderr)
        return 1

    if args.dry_run:
        for stem, repo, kind in all_targets:
            n = len((CARDS_DIR / f"{stem}.md").read_text().splitlines())
            print(f"[dry-run] would push hub_cards/{stem}.md ({n} lines) -> <user>/{repo} [{kind}]")
        return 0

    token = os.environ.get("HF_TOKEN")
    if not token:
        print("Set HF_TOKEN (write scope) in the environment.", file=sys.stderr)
        return 1

    from huggingface_hub import HfApi
    from huggingface_hub.utils import RepositoryNotFoundError

    api = HfApi(token=token)
    user = api.whoami()["name"]
    failed = []
    for stem, repo_name, kind in all_targets:
        repo = f"{user}/{repo_name}"
        path = CARDS_DIR / f"{stem}.md"
        url = f"https://huggingface.co/{'datasets/' if kind == 'dataset' else ''}{repo}"
        try:
            api.upload_file(
                path_or_fileobj=str(path),
                path_in_repo="README.md",
                repo_id=repo,
                repo_type=kind,
                commit_message="Update card (generated from committed eval results)",
            )
            print(f"pushed {path.name} -> {url}")
        except RepositoryNotFoundError:
            print(f"SKIP {repo} [{kind}]: repo not found or no write access", file=sys.stderr)
            failed.append(repo_name)
        except Exception as exc:  # noqa: BLE001 - report and continue over the rest
            print(f"FAIL {repo} [{kind}]: {type(exc).__name__}: {exc}", file=sys.stderr)
            failed.append(repo_name)

    print(f"\n{len(all_targets) - len(failed)}/{len(all_targets)} cards pushed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
